#!/bin/bash
# Debug script to trace PC corruption

echo "Compiling test case..."
RUST_LOG=error cargo run --bin grue-compiler -- debug_object_error.grue > /dev/null 2>&1

echo "Generated bytecode around entry:"
xxd -g 1 -l 32 -s 0x730 debug_object_error.z3

echo "Running with PC tracing..."
RUST_LOG=debug timeout 3s cargo run --bin gruesome debug_object_error.z3 2>&1 | head -50